//
//  BAImporter.swift
//  BattleAnimationCore
//
//  Created by Matt Gannon on 8/3/26.
//
//  This code was generated by OpenAI Codex.

import BAModel
import Foundation
import ImageUtilities
import ScriptParser

enum BAImportError: Error {
    case noFramesFound
}

public final class BAImporter {
    public init() {}

    public func importAnimation(
        animationID: String,
        sourceFolder: URL,
        scriptURL: URL,
        outputFolder: URL
    ) throws -> BAManifest {
        // Parse the FE animation script into mode timelines.
        let scriptText = try String(contentsOf: scriptURL, encoding: .utf8)
        let script = BAScriptParser.parse(scriptText)

        // Ensure the processed animation folder exists.
        try FileManager.default.createDirectory(
            at: outputFolder,
            withIntermediateDirectories: true
        )

        // Unknown modes are preserved as warnings for now.
        let usableModes = script.modes.filter { $0.id != .unknown }

        var warnings = script.modes
            .filter { $0.id == .unknown }
            .map { "Skipping unknown mode \($0.rawModeNumber)" }

        // Process each source frame only once, even if modes share it.
        let uniqueFrameFiles = Array(
            Set(usableModes.flatMap { $0.frames.map(\.filename) })
        )
            .sorted()

        guard !uniqueFrameFiles.isEmpty else {
            throw BAImportError.noFramesFound
        }

        var preservedPalette: [RGBA] = []

        let framesFolder = outputFolder.appendingPathComponent("frames")

        // Convert unique FE source frames into SpriteKit-friendly PNG assets.
        let frameAssets = try uniqueFrameFiles.compactMap { filename in
            try processFrameAsset(
                filename: filename,
                sourceFolder: sourceFolder,
                framesFolder: framesFolder,
                preservedPalette: &preservedPalette,
                warnings: &warnings
            )
        }

        // Convert FE modes into timelines that reference shared frame assets.
        let timelines = usableModes.map { mode in
            makeTimeline(from: mode)
        }

        return BAManifest(
            id: animationID,
            sourceScript: scriptURL.lastPathComponent,
            renderSize: .combatFrameSize,
            frameAssets: frameAssets,
            timelines: timelines,
            preservedPalette: preservedPalette,
            warnings: warnings
        )
    }

    private func processFrameAsset(
        filename: String,
        sourceFolder: URL,
        framesFolder: URL,
        preservedPalette: inout [RGBA],
        warnings: inout [String]
    ) throws -> BAManifest.Frame.Asset? {
        // Load the original community-format PNG.
        let sourceURL = sourceFolder.appendingPathComponent(filename)
        let image = try PNGLoader.load(from: sourceURL)

        // Preserve the embedded palette marker for later palette work.
        let palette = image.extractTopRightPalette()

        if preservedPalette.isEmpty {
            preservedPalette = palette
        }

        // The actual top-right pixel is the chroma/transparent color.
        let transparentColor = image.pixel(x: image.width - 1, y: 0)

        let sourceStem = sourceURL.deletingPathExtension().lastPathComponent

        // Each source frame gets its own folder to avoid duplicate filenames.
        try FileManager.default.createDirectory(
            at: framesFolder,
            withIntermediateDirectories: true
        )

        switch FrameClassifier.classify(width: image.width, height: image.height) {
        case .normal:
            // Normal frames contain one visible 240x160 layer.
            let fileName = "\(sourceStem)_main.png"
            let relativePath = "frames/\(fileName)"
            let outputURL = framesFolder.appendingPathComponent(fileName)

            let processed = image
                .cropped(x: 0, y: 0, width: 240, height: 160)
                .replacingColorWithTransparency(transparentColor)

            try PNGWriter.write(png: processed, to: outputURL)

            return BAManifest.Frame.Asset(
                sourceFile: filename,
                layerType: .main(path: relativePath)
            )

        case .piercing:
            // Piercing frames contain separate background and foreground layers.
            let backgroundName = "\(sourceStem)_background.png"
            let foregroundName = "\(sourceStem)_foreground.png"
            let backgroundPath = "frames/\(backgroundName)"
            let foregroundPath = "frames/\(foregroundName)"
            let backgroundURL = framesFolder.appendingPathComponent(backgroundName)
            let foregroundURL = framesFolder.appendingPathComponent(foregroundName)

            // The left 240px region is drawn in front of the defender.
            let foreground = image
                .cropped(x: 0, y: 0, width: 240, height: 160)
                .replacingColorWithTransparency(transparentColor)

            // The middle 240px region is drawn behind of the defender.
            let background = image
                .cropped(x: 240, y: 0, width: 240, height: 160)
                .replacingColorWithTransparency(transparentColor)

            try PNGWriter.write(png: background, to: backgroundURL)
            try PNGWriter.write(png: foreground, to: foregroundURL)

            return BAManifest.Frame.Asset(
                sourceFile: filename,
                layerType: .piercing(foreground: foregroundPath, background: backgroundPath)
            )

        case .unsupported(let width, let height):
            // Unsupported sizes are skipped but reported in the manifest.
            warnings.append("Unsupported frame size \(width)x\(height): \(filename)")
            return nil
        }
    }

    private func makeTimeline(from mode: BAMode) -> BAManifest.Timeline {
        // Preserve the original event order from the FE script.
        let events = mode.events.compactMap { event -> BAManifest.Timeline.Event? in
            switch event {
            case .frame(let frame):
                return .frame(
                    BAManifest.Frame.Event(
                        sourceFile: frame.filename,
                        duration: frame.durationSeconds
                    )
                )

            case .command(let command):
                return .command(command)
            }
        }

        return BAManifest.Timeline(
            modeID: mode.id,
            rawModeNumber: mode.rawModeNumber,
            title: mode.title,
            events: events
        )
    }
}
