//
//  BAImporter.swift
//  BattleAnimationCore
//
//  Created by Matt Gannon on 8/3/26.
//
//  This code was generated by OpenAI Codex.

import BAModel
import Foundation
import GameModels
import ImageUtilities
import ScriptParser

enum BAImportError: LocalizedError {
    case noFramesFound(folderName: String)
    case unsupportedFrameSize(filename: String, width: Int, height: Int)
    case paletteExceedsCapacity(animationID: String)
    case paletteMismatch(animationID: String, frame: String, color: RGBA)
    case paletteSwatchMismatch(animationID: String, frame: String)

    var errorDescription: String? {
        switch self {
        case .noFramesFound(let folderName):
            "No frames found for \(folderName)"
        case .unsupportedFrameSize(let filename, let width, let height):
            "Unsupported frame size \(width) x \(height) - file \(filename)"
        case .paletteExceedsCapacity:
            "Palette exceeded capacity"
        case .paletteMismatch(_, let frame, _):
            "Mismatched palettes in frame [\(frame)]"
        case .paletteSwatchMismatch(_, let frame):
            "Swatch mismatch in frame [\(frame)]"
        }
    }
}

public final class BAImporter {
    public init() {}

    public func importAnimation(
        animationID: AnimationID,
        spriteSet: BASpriteSet,
        variant: BAVariant,
        sourceFolder: URL,
        scriptURL: URL,
        outputFolder: URL
    ) throws -> BAManifest {
        // Parse the FE animation script into mode timelines.
        let scriptText = try String(contentsOf: scriptURL, encoding: .utf8)
        let script = BAScriptParser.parse(scriptText)

        // Ensure the processed animation folder exists.
        try FileManager.default.createDirectory(
            at: outputFolder,
            withIntermediateDirectories: true
        )

        // Unknown modes are preserved as warnings for now.
        let usableModes = script.modes.filter(\.modeID.isKnown)

        var warnings = script.modes
            .filter(\.modeID.isUnknown)
            .map { "Skipping unknown mode \(String(describing: $0.modeID))" }

        // Process each source frame only once, even if modes share it.
        let uniqueFrameFiles = Array(
            Set(usableModes.flatMap { $0.frames.map(\.filename) })
        ).sorted()

        guard !uniqueFrameFiles.isEmpty else {
            throw BAImportError.noFramesFound(folderName: sourceFolder.relativePath)
        }

        let framesFolder = outputFolder.appendingPathComponent("frames")

        var paletteBuilder = PaletteTableBuilder()
        var establishedSwatch: [RGBA]?

        let frameAssets = try uniqueFrameFiles.compactMap { filename -> BAManifest.Frame.Asset? in
            let sourceURL = sourceFolder.appendingPathComponent(filename)
            let image = try PNGLoader.load(from: sourceURL)
            let swatch = image.extractTopRightPalette()

            if let establishedSwatch {
                guard swatch == establishedSwatch else {
                    throw BAImportError.paletteSwatchMismatch(animationID: animationID, frame: filename)
                }
            } else {
                var normalizedSwatch = swatch
                normalizedSwatch[7] = RGBA(
                    r: normalizedSwatch[7].r,
                    g: normalizedSwatch[7].g,
                    b: normalizedSwatch[7].b,
                    a: 0
                )
                paletteBuilder.establish(from: normalizedSwatch)
                establishedSwatch = swatch
            }

            return try processFrameAsset(
                image: image,
                filename: filename,
                sourceFolder: sourceFolder,
                framesFolder: framesFolder,
                animationID: animationID,
                paletteBuilder: paletteBuilder,
                warnings: &warnings
            )
        }

        // Convert FE modes into timelines that reference shared frame assets.
        let timelines = usableModes.map { mode in
            makeTimeline(from: mode)
        }

        return BAManifest(
            id: animationID,
            spriteSet: spriteSet,
            variant: variant,
            sourceScript: scriptURL.lastPathComponent,
            renderSize: .combatFrameSize,
            frameAssets: frameAssets,
            timelines: timelines,
            paletteTable: paletteBuilder.table,
            warnings: warnings
        )
    }

    private func processFrameAsset(
        image: PixelImage,
        filename: String,
        sourceFolder: URL,
        framesFolder: URL,
        animationID: AnimationID,
        paletteBuilder: PaletteTableBuilder,
        warnings: inout [String]
    ) throws -> BAManifest.Frame.Asset {

        // Load the original community-format PNG.
        let sourceURL = sourceFolder.appendingPathComponent(filename)
        let image = try PNGLoader.load(from: sourceURL)

        // The actual top-right pixel is the chroma/transparent color.
        let transparentColor = image.pixel(x: image.width - 1, y: 0)

        let sourceStem = sourceURL.deletingPathExtension().lastPathComponent

        // Each source frame gets its own folder to avoid duplicate filenames.
        try FileManager.default.createDirectory(
            at: framesFolder,
            withIntermediateDirectories: true
        )

        switch FrameClassifier.classify(width: image.width, height: image.height) {
        case .normal:
            // Normal frames contain one visible 240x160 layer.
            let processed = image
                .cropped(x: 0, y: 0, width: 240, height: 160)
                .replacingColorWithTransparency(transparentColor)

            let pngPath = try writePNG(
                for: processed, animationID: animationID, framesFolder: framesFolder, stem: sourceStem, qualifier: .main
            )

            let palettePath = try writePaletteIndex(
                for: processed, paletteBuilder: paletteBuilder, animationID: animationID, framesFolder: framesFolder, stem: sourceStem, qualifier: .main
            )

            return BAManifest.Frame.Asset(
                sourceFile: filename,
                layerType: .single(pngPath),
                paletteLayers: .single(palettePath)
            )

        case .piercing:
            // The left 240px region is drawn in front of the defender.
            let foreground = image
                .cropped(x: 0, y: 0, width: 240, height: 160)
                .replacingColorWithTransparency(transparentColor)

            // The middle 240px region is drawn behind of the defender.
            let background = image
                .cropped(x: 240, y: 0, width: 240, height: 160)
                .replacingColorWithTransparency(transparentColor)

            // Write the PNGs
            let fgPath = try writePNG(
                for: foreground, animationID: animationID, framesFolder: framesFolder, stem: sourceStem, qualifier: .foreground
            )
            let bgPath = try writePNG(
                for: background, animationID: animationID, framesFolder: framesFolder, stem: sourceStem, qualifier: .background
            )

            // Store the palettes
            let fgPalettePath = try writePaletteIndex(
                for: foreground, paletteBuilder: paletteBuilder, animationID: animationID, framesFolder: framesFolder, stem: sourceStem, qualifier: .foreground
            )
            let bgPalettePath = try writePaletteIndex(
                for: background, paletteBuilder: paletteBuilder, animationID: animationID, framesFolder: framesFolder, stem: sourceStem, qualifier: .background
            )

            return BAManifest.Frame.Asset(
                sourceFile: filename,
                layerType: .dual(foreground: fgPath, background: bgPath),
                paletteLayers: .dual(foreground: fgPalettePath, background: bgPalettePath)
            )

        case .unsupported(let width, let height):
            // Unsupported sizes are skipped but reported in the manifest.
            throw BAImportError.unsupportedFrameSize(filename: filename, width: width, height: height)
        }
    }

    private enum FilePathQualifier: String {
        case main, foreground, background
    }

    private func writePNG(
        for image: PixelImage,
        animationID: AnimationID,
        framesFolder: URL,
        stem: String,
        qualifier: FilePathQualifier
    ) throws -> String {
        let fileName = "\(stem)_\(qualifier.rawValue).png"
        let url = framesFolder.appendingPathComponent(fileName)
        try PNGWriter.write(png: image, to: url)
        return "frames/\(fileName)"
    }

    private func writePaletteIndex(
        for image: PixelImage,
        paletteBuilder: PaletteTableBuilder,
        animationID: AnimationID,
        framesFolder: URL,
        stem: String,
        qualifier: FilePathQualifier
    ) throws -> String {
        let fileName = "\(stem)_\(qualifier.rawValue).idx"
        let indices = try paletteBuilder.indices(for: image, frame: fileName, animationID: animationID)
        let url = framesFolder.appendingPathComponent(fileName)
        try IndexBufferWriter.write(indices: indices, to: url)
        return "frames/\(fileName)"
    }

    private func makeTimeline(from mode: BAMode) -> BAManifest.Timeline {
        // Preserve the original event order from the FE script.
        let events = mode.events.compactMap { event -> BAManifest.Timeline.Event? in
            switch event {
            case .frame(let frame):
                return .frame(
                    BAManifest.Frame.Event(
                        sourceFile: frame.filename,
                        durationTicks: frame.durationTicks
                    )
                )

            case .command(let command):
                return .command(command)
            }
        }

        return BAManifest.Timeline(
            modeID: mode.modeID,
            title: mode.title,
            events: events
        )
    }
}
