//
//  BattleAnimationScriptParser.swift
//  BattleAnimationCore
//
//  Created by Matt Gannon on 8/3/26.
//
//  This code was generated by OpenAI Codex.

import Foundation

public enum BAScriptParser {

    private static let modeLinesTerminator = "~~~"

    public static func parse(_ text: String) -> BAScript {
        var modeTitlesByID: [Int: String] = [:]
        var modeEventsByID: [Int: [BAScript.Event]] = [:]
        var currentModeNumber: Int?

        for rawLine in text.split(whereSeparator: \.isNewline).map(String.init) {
            let line = rawLine.trimmingCharacters(in: .whitespacesAndNewlines)

            // Ignore empty or comment lines
            guard !line.isEmpty, !line.hasPrefix("#") else { continue }

            // Check if we are beginning to track a new mode
            // The title is unused but reserved for potential debugging.
            if let header = parseModeHeader(line) {
                currentModeNumber = header.rawModeNumber
                if let title = header.title {
                    modeTitlesByID[header.rawModeNumber] = title
                }
                continue
            }

            // Check if we are done with our current mode (~~~)
            if line == modeLinesTerminator {
                currentModeNumber = nil
                continue
            }

            // Now we know an existing currentModeID is current.
            // Parse the relevant frame or command and continue
            guard let currentModeNumber else { continue }

            if let frame = parseFrameLine(line) {
                modeEventsByID[currentModeNumber, default: []].append(.frame(frame))
                continue
            }

            if let command = parseCommandLine(line) {
                modeEventsByID[currentModeNumber, default: []].append(.command(command))
                continue
            }
        }

        // Build the modes from our dictionary
        let modes = modeEventsByID
            .map { (rawNumber, events) in
                return BAMode(
                    rawModeNumber: rawNumber,
                    id: BAModeID(rawModeNumber: rawNumber),
                    title: modeTitlesByID[rawNumber],
                    events: events
                )
            }

        return BAScript(modes: modes)
    }


//    static func parse(_ text: String) -> BAScript {
//        var modes: [BAMode] = []
//        var currentMode: BAMode?
//        var modeEvents: [BAModeID: BAScript.Event] = [:]
//
//
//        for rawLine in text.split(whereSeparator: \.isNewline).map(String.init) {
//            let line = rawLine.trimmingCharacters(in: .whitespacesAndNewlines)
//
//            guard !line.isEmpty,
//                  !line.hasPrefix("#")
//            else { continue }
//            
//
//            if let header = parseModeHeader(line) {
//                if let currentMode {
//                    modes.append(currentMode)
//                }
//
//                currentMode = BAMode(
//                    rawModeNumber: header.rawModeNumber,
//                    id: BAModeID(rawModeNumber: header.rawModeNumber),
//                    title: header.title,
//                    events: []
//                )
//
//                continue
//            }
//
//            if line == "~~~" {
//                if let currentMode {
//                    modes.append(currentMode)
//                }
//
//                currentMode = nil
//                continue
//            }
//
//            guard currentMode != nil else { continue }
//
//            if let frame = parseFrameLine(line) {
//                currentMode?.events.append(.frame(frame))
//                continue
//            }
//
//            if let command = parseCommandLine(line) {
//                currentMode?.events.append(.command(command))
//                continue
//            }
//        }
//
//        if let currentMode {
//            modes.append(currentMode)
//        }
//
//        return BattleAnimationScript(modes: modes)
//    }

    private struct ModeHeader {
        let rawModeNumber: Int
        let title: String?
    }

    private static func parseModeHeader(_ line: String) -> ModeHeader? {
        guard line.hasPrefix("///") else { return nil }

        let parts = splitComment(line)
        let body = parts.body

        guard let range = body.range(of: "Mode ") else { return nil }

        let afterMode = body[range.upperBound...]
        let numberText = afterMode
            .prefix { $0.isNumber }

        guard let number = Int(numberText) else { return nil }

        return ModeHeader(
            rawModeNumber: number,
            title: parts.comment
        )
    }

    private static func parseCommandLine(_ line: String) -> BAScript.Command? {
        let parts = splitComment(line)
        let body = parts.body.trimmingCharacters(in: .whitespacesAndNewlines)

        guard body.hasPrefix("C") else { return nil }

        return BAScript.Command(
            code: body,
            comment: parts.comment
        )
    }

    private static func parseFrameLine(_ line: String) -> BAScript.FrameReference? {
        let partsWithoutComment = splitComment(line).body
        let parts = partsWithoutComment.split(separator: " ", omittingEmptySubsequences: true)

        guard parts.count >= 3 else { return nil }
        guard let ticks = Int(parts[0]) else { return nil }

        let flags = String(parts[1])
        let filename = String(parts[2])

        guard filename.lowercased().hasSuffix(".png") else { return nil }

        return BAScript.FrameReference(
            durationTicks: ticks,
            flags: flags,
            filename: filename
        )
    }

    private static func splitComment(_ line: String) -> (body: String, comment: String?) {
        let pieces = line.split(separator: "#", maxSplits: 1, omittingEmptySubsequences: false)

        let body = String(pieces[0])
            .trimmingCharacters(in: .whitespacesAndNewlines)

        let comment = pieces.count > 1
        ? String(pieces[1]).trimmingCharacters(in: .whitespacesAndNewlines)
        : nil

        return (body, comment?.isEmpty == true ? nil : comment)
    }

    /*
    private static func confirmHeaderLine(_ headerLine: String) -> Bool {
        return headerLine.hasPrefix("///") && headerLine.contains("Mode")
    }

    private static func rawModeNumber(from headerLine: String) -> Int? {
        guard confirmHeaderLine(headerLine) else { return nil }
        let numberText = stripComment(from: headerLine)
            .filter { $0.isNumber }
        return Int(numberText)
    }

    private static func stripComment(from line: String) -> String {
        return splitComment(line).body
    }
     */
}
