//
//  PixelImage.swift
//  BattleAnimationCore
//
//  Created by Matt Gannon on 8/3/26.
//
//  This code was generated by OpenAI Codex.

import Foundation
import CoreGraphics
import ImageIO
import UniformTypeIdentifiers

public struct PixelImage {
    public var width: Int
    public var height: Int
    public var pixels: [RGBA]

    public func pixel(x: Int, y: Int) -> RGBA {
        pixels[y * width + x]
    }

    public func extractTopRightPalette() -> [RGBA] {
        guard width >= 8, height >= 2 else { return [] }

        var colors: [RGBA] = []

        for y in 0..<2 {
            for x in (width - 8)..<width {
                colors.append(pixel(x: x, y: y))
            }
        }

        return colors
    }

    public func cropped(x originX: Int, y originY: Int, width cropWidth: Int, height cropHeight: Int) -> PixelImage {
        var output: [RGBA] = []
        output.reserveCapacity(cropWidth * cropHeight)

        for y in originY..<(originY + cropHeight) {
            for x in originX..<(originX + cropWidth) {
                output.append(pixel(x: x, y: y))
            }
        }

        return PixelImage(width: cropWidth, height: cropHeight, pixels: output)
    }

    public func replacingColorWithTransparency(_ color: RGBA) -> PixelImage {
        let converted = pixels.map { pixel in
            pixel.matchesRGB(color)
            ? RGBA(r: pixel.r, g: pixel.g, b: pixel.b, a: 0)
            : pixel
        }

        return PixelImage(width: width, height: height, pixels: converted)
    }
}

extension RGBA {
    func matchesRGB(_ other: RGBA) -> Bool {
        r == other.r && g == other.g && b == other.b
    }
}
