//
//  BAProcessedAnimationStore.swift
//  BattleAnimationCore
//
//  Created by Matt Gannon on 8/3/26.
//
//  This code was generated by OpenAI Codex.

import BAModel
import Foundation

public enum BAProcessedAnimationStoreError: Error {
    case manifestNotFound(String)
    case frameAssetNotFound(paths: [String])
    case noTimelineForMode(BAModeID)
}

public struct BAPlaybackFrame {
    public let duration: TimeInterval
    public let layerURLs: LayerURLs

    public enum LayerURLs {
        case single(URL)
        case double(foreground: URL, background: URL)
    }
}

public enum BAProcessedAnimationStore {
    static func loadManifest(
        id: String
    ) throws -> BAManifest {
        // Processed animations are bundled as copied package resources.
        guard let manifestURL = Bundle.module.url(
            forResource: "manifest",
            withExtension: "json",
            subdirectory: "ProcessedAnimations/\(id)"
        ) else {
            throw BAProcessedAnimationStoreError.manifestNotFound(id)
        }

        let data = try Data(contentsOf: manifestURL)
        return try JSONDecoder().decode(BAManifest.self, from: data)
    }

    public static func playableFrames(
        animationID: String,
        modeID rawModeNumber: Int
    ) throws -> [BAPlaybackFrame] {
        // Load manifest and find the requested FE mode timeline.
        let manifest = try loadManifest(id: animationID)

        // TODO: Need fallback for nonexistent Modes.
        let modeID = BAModeID(rawModeNumber: rawModeNumber)
        guard let timeline = manifest.timelines.first(where: { $0.modeID == modeID }) else {
            throw BAProcessedAnimationStoreError.noTimelineForMode(modeID)
        }

        // Build a lookup from original source PNG name to processed frame asset.
        let assetsBySourceFile = Dictionary(
            uniqueKeysWithValues: manifest.frameAssets.map { ($0.sourceFile, $0) }
        )

        let frameEvents = timeline.events.compactMap {
            switch $0 {
            case .frame(let frameEvent): frameEvent
            default: nil
            }
        }

        let frames: [BAPlaybackFrame] = try frameEvents.compactMap { frameEvent in
            guard let asset = assetsBySourceFile[frameEvent.sourceFile] else { return nil }
            let layerURLs = try playbackLayerURLs(from: asset.layerType, animationID: animationID)
            return BAPlaybackFrame(
                duration: frameEvent.duration,
                layerURLs: layerURLs
            )
        }

        return frames
    }

    private static func playbackLayerURLs(
        from assetPaths: BAManifest.Frame.LayerType,
        animationID: String
    ) throws(BAProcessedAnimationStoreError) -> BAPlaybackFrame.LayerURLs {
        switch assetPaths {
        case .main(let path):
            guard let pathURL = imageURL(path: path, animationID: animationID) else {
                throw .frameAssetNotFound(paths: assetPaths.paths)
            }
            return .single(pathURL)
        case .piercing(let fgPath, let bgPath):
            guard let fgPathURL = imageURL(path: fgPath, animationID: animationID),
                  let bgPathURL = imageURL(path: bgPath, animationID: animationID)
            else {
                throw .frameAssetNotFound(paths: assetPaths.paths)
            }
            return .double(foreground: fgPathURL, background: bgPathURL)
        }
    }

    private static func imageURL(path: String, animationID: String) -> URL? {
        Bundle.module.url(
            forResource: (path as NSString).deletingPathExtension,
            withExtension: (path as NSString).pathExtension,
            subdirectory: "ProcessedAnimations/\(animationID)"
        )
    }
}
