//
//  BAImportTool.swift
//  BattleAnimationCore
//
//  Created by Matt Gannon on 8/3/26.
//
//  This code was generated by OpenAI Codex.

import Foundation
import BattleAnimationCore

@main
struct BAImportTool {
    static func main() {
        do {
            try run()
        } catch {
            print("Import failed: \(error)")
            exit(1)
        }
    }

    private static func run() throws {
        // The tool should be run from the package root.
        let packageRoot = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)

        let sourceRoot = packageRoot
            .appendingPathComponent("Sources/BattleAnimationCore/Resources/SourceAnimations")

        let outputRoot = packageRoot
            .appendingPathComponent("Sources/BattleAnimationCore/Resources/ProcessedAnimations")

        // Recursively find folders that contain parseable FE animation scripts.
        let sourceFolders = try animationSourceFolders(in: sourceRoot)

        guard !sourceFolders.isEmpty else {
            print("No source animation folders found at \(sourceRoot.path)")
            return
        }

        let importer = BAImporter()

        for sourceFolder in sourceFolders {
            let animationID = animationID(for: sourceFolder, sourceRoot: sourceRoot)
            let scriptURL = try findParseableScript(in: sourceFolder)
            let outputFolder = outputRoot.appendingPathComponent(animationID)

            // Remove stale generated files before re-importing.
            if FileManager.default.fileExists(atPath: outputFolder.path) {
                try FileManager.default.removeItem(at: outputFolder)
            }

            // Recreate the animation output folder.
            try FileManager.default.createDirectory(
                at: outputFolder,
                withIntermediateDirectories: true
            )

            // Import the animation into its processed output folder.
            let manifest = try importer.importAnimation(
                animationID: animationID,
                sourceFolder: sourceFolder,
                scriptURL: scriptURL,
                outputFolder: outputFolder
            )

            let manifestURL = outputFolder.appendingPathComponent("manifest.json")
            let manifestData = try JSONEncoder.prettyStable.encode(manifest)

            // Write the generated animation manifest next to the frames folder.
            try manifestData.write(to: manifestURL)

            print("Imported \(animationID): \(manifest.frameAssets.count) frame assets, \(manifest.timelines.count) timelines")
        }
    }

    private static func animationSourceFolders(in sourceRoot: URL) throws -> [URL] {
        // A source folder must contain both PNG frames and a parseable script.
        try recursiveSubdirectories(of: sourceRoot)
            .filter { sourceFolder in
                guard try containsPNG(in: sourceFolder) else { return false }
                return (try? findParseableScript(in: sourceFolder)) != nil
            }
            .sorted { $0.path < $1.path }
    }

    private static func recursiveSubdirectories(of root: URL) throws -> [URL] {
        let fileManager = FileManager.default

        guard let enumerator = fileManager.enumerator(
            at: root,
            includingPropertiesForKeys: [.isDirectoryKey],
            options: [.skipsHiddenFiles]
        ) else {
            return []
        }

        var directories: [URL] = []

        // Walk every nested folder under SourceAnimations.
        for case let url as URL in enumerator {
            let values = try url.resourceValues(forKeys: [.isDirectoryKey])

            if values.isDirectory == true {
                directories.append(url)
            }
        }

        return directories
    }

    private static func containsPNG(in folder: URL) throws -> Bool {
        let files = try FileManager.default.contentsOfDirectory(
            at: folder,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]
        )

        // Frame source folders should contain PNG files directly.
        return files.contains { $0.pathExtension.lowercased() == "png" }
    }

    private static func findParseableScript(in sourceFolder: URL) throws -> URL {
        let files = try FileManager.default.contentsOfDirectory(
            at: sourceFolder,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]
        )

        let candidates = files
            .filter { $0.pathExtension.lowercased() == "txt" }
            .filter { !isIgnoredTextFile($0) }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }

        // Prefer the first text file that actually parses into FE modes.
        for candidate in candidates {
            let text = try String(contentsOf: candidate, encoding: .utf8)
            let script = BAScriptParser.parse(text)

            if !script.modes.isEmpty {
                return candidate
            }
        }

        throw BAImportToolError.noParseableScriptFound(sourceFolder)
    }

    private static func isIgnoredTextFile(_ url: URL) -> Bool {
        let name = url.lastPathComponent.lowercased()
        let stem = url.deletingPathExtension().lastPathComponent.lowercased()

        // These text files are documentation, not animation scripts.
        return name == "readme.txt"
        || name == "credits.txt"
        || stem.contains("without_comment")
    }

    private static func animationID(for sourceFolder: URL, sourceRoot: URL) -> String {
        let relativePath = sourceFolder.path
            .replacingOccurrences(of: sourceRoot.path + "/", with: "")

        // Nested source paths become stable processed animation identifiers.
        return relativePath
            .split(separator: "/")
            .map(String.init)
            .map(cleanAnimationIDComponent)
            .joined(separator: "_")
    }

    private static func cleanAnimationIDComponent(_ component: String) -> String {
        // Remove community repo ordering prefixes like "4. Handaxe".
        let trimmed = component.trimmingCharacters(in: .whitespacesAndNewlines)
        let parts = trimmed.split(separator: " ", maxSplits: 1, omittingEmptySubsequences: true)

        guard parts.count == 2 else {
            return trimmed
        }

        let possibleOrdinal = parts[0]

        guard possibleOrdinal.hasSuffix(".") else {
            return trimmed
        }

        let numberPart = possibleOrdinal.dropLast()

        guard numberPart.allSatisfy(\.isNumber) else {
            return trimmed
        }

        return String(parts[1])
    }}

enum BAImportToolError: Error {
    case noParseableScriptFound(URL)
}
