//
//  SourceFrameKind.swift
//  BattleAnimationCore
//
//  Created by Matt Gannon on 8/3/26.
//
//  This code was generated by OpenAI Codex.

import Foundation

public enum SourceFrameKind {
    case normal
    case piercing
    case unsupported(width: Int, height: Int)
}

public enum FrameClassifier {
    private static let standardBattleFrameWidth: Int = 248
    private static let standardBattleFrameHeight: Int = 160

    private static let standardPiercingFrameWidth: Int = 488
    private static let standardPiercingFrameHeight: Int = 160

    public static func classify(width: Int, height: Int) -> SourceFrameKind {
        switch (width, height) {
        case (standardBattleFrameWidth, standardBattleFrameHeight):
            return .normal
        case (standardPiercingFrameWidth, standardPiercingFrameHeight):
            return .piercing
        default:
            return .unsupported(width: width, height: height)
        }
    }
}
